### ISSUE TITLE
[Feature Request ] Automatic Rotation Of access key with AWS iam Roles anywhere service

### ISSUE THREAD

**Issue by krimeshshah** [credativ/vali#30]
Currently we use  AWS s3 bucket to store monitoring data  which can be accessed using AccessKey ID and Access key credentials. As per our security standard we are supposed to rotate the AccessKey every 1 months which becomes manual task for us. I found the solution to use temperoary credentials generated by AWS IAM roles anywhere service which is the alternate of aws secret manager. AWS iam roles anywhere server acts as a workload identity provider for the clients/services out side of aws cloud to access aws services. Reference AWS documentation - https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html

Is it possible to provide this feature in vali?

**Comment by ntap-nmarco** [comment]
No, I am sorry. For now we are not planning to build that feature.

However, we will add this to our list and if anything changes, we will reopen this issue.
